sudo: required
services:
  - docker

before_install:
  - docker build -t vivekshetty/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vivekshetty/react-test npm  test

after_success:
  - docker build -t vivekshetty/multi-client:latest ./client
  - docker build -t vivekshetty/multi-nginx:latest ./nginx
  - docker build -t vivekshetty/multi-server:latest ./server
  - docker build -t vivekshetty/multi-worker:latest ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" docker.io --password-stdin
  - docker push vivekshetty/multi-client:latest
  - docker push vivekshetty/multi-nginx:latest
  - docker push vivekshetty/multi-server:latest
  - docker push vivekshetty/multi-worker:latest
