sudo: required
services:
  - docker

before_install:
  - docker build -t vivekshetty1984/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vivekshetty1984/react-test npm  test

after_success:
  - docker build -t vivekshetty1984/multi-client ./client
  - docker build -t vivekshetty1984/multi-nginx ./nginx
  - docker build -t vivekshetty1984/multi-server ./server
  - docker build -t vivekshetty1984/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push vivekshetty1984/multi-client
  - docker push vivekshetty1984/multi-nginx
  - docker push vivekshetty1984/multi-server
  - docker push vivekshetty1984/multi-worker
